version: '3'
services:
  dltc-env-server:
    image: philosophiech/dltc-env:latest
    container_name: dltc-env
    tty: true
    stdin_open: true
    hostname: dltc-env
    volumes:
      - "${DLTC_WORKHOUSE_DIRECTORY}:/home/copyeditor/dltc-workhouse"
    working_dir: /home/copyeditor/dltc-workhouse
    command: ["LaunchScript", "start"]
