#!/usr/bin/env bash

# Entrypoint for the container

#DLTC_WORKHOUSE_DIR="/dltc-workhouse"

#cd ${DLTC_WORKHOUSE_DIR}


case "$1" in

    "start")
        # Keep the container alive
        while true; do sleep 1000; done
        ;;

    "pandoc" | "pandoc-crossref")
        "/usr/local/bin/${1}" ${@:2}
        exit 0 ;;

    "inkscape")
        /usr/bin/inkscape ${@:2}
        exit 0 ;;

    "pdflatex" | "xelatex" | "bibtex" | "latexmk" | "synctex" | "texcount" | "latexindent")
        "/opt/texlive/texdir/bin/default/${1}" ${@:2}
        exit 0 ;;

    *)
        echo "LaunchScript: Invalid argument ENTRYPOINT ARGUMENT: ${@:2}"
        # TODO:
        #echo "Call -h or --help to see the valid ENTRYPOINT ARGUMENTS."
        exit 1 ;;

esac

