#!/usr/bin/env bash

# Entrypoint for the container

#DLTC_WORKHOUSE_DIR="/dltc-workhouse"

#cd ${DLTC_WORKHOUSE_DIR}

case "$1" in

    "ssh")
        if ! pgrep sshd > /dev/null; then
            echo "LaunchScript: Starting SSH server..."
            service ssh start && echo "LaunchScript: SSH server started."
            rm -rf ${HOME}/.ssh
            mkdir ${HOME}/.ssh
            wget https://raw.githubusercontent.com/alebg/dltc-compilation-env/alebg/issue7/copyeditor%20files/copyediting_team_public_keys -O ${HOME}/.ssh/authorized_keys
            echo "" >> ${HOME}/.ssh/authorized_keys
        else
            echo "LaunchScript: SSH server already running."
        fi

        # Keep the container alive
        while true; do sleep 1000; done

        exit 0 ;;

    "pandoc" | "pandoc-crossref")
        "/usr/local/bin/${1}" ${@:2}
        exit 0 ;;

    "inkscape")
        /usr/bin/inkscape ${@:2}
        exit 0 ;;

    "pdflatex" | "xelatex" | "bibtex" | "latexmk" | "synctex" | "texcount" | "latexindent")
        "/opt/texlive/texdir/bin/default/${1}" ${@:2}
        exit 0 ;;

    *)
        echo "LaunchScript: Invalid argument ENTRYPOINT ARGUMENT: ${@:2}"
        # TODO:
        #echo "Call -h or --help to see the valid ENTRYPOINT ARGUMENTS."
        exit 1 ;;

esac

